package com.odin.profileservice.enums;
public enum StatusReadinessReason {
    MIDDLEWARE_USER_MISSING, GLOBAL_HASH_MISSING, GLOBAL_HASH_INVALID,
    PRIVACY_STATE_MISSING, CONTACT_SYNC_REQUIRED, CONTACT_TARGETS_UNRESOLVED, ACCOUNT_INACTIVE,
    ACCOUNT_NOT_FOUND, HASH_VERSION_UNSUPPORTED, DATA_INTEGRITY_CONFLICT,
    DEPENDENCY_FAILURE
}
