package com.odin.profileservice.enums;

public enum StatusEligibilityReason {
    ALLOWED_FORWARD_CONTACT,
    SELF,
    NO_FORWARD_CONTACT,
    BLOCKED_BY_UPLOADER,
    BLOCKED_BY_VIEWER,
    EXPLICITLY_HIDDEN,
    UPLOADER_NOT_FOUND,
    UPLOADER_INACTIVE,
    VIEWER_NOT_FOUND,
    VIEWER_INACTIVE,
    UNRESOLVED_CONTACT_TARGET,
    DEPENDENCY_FAILURE,
    DATA_INTEGRITY_FAILURE,
    STATUS_REPAIR_REQUIRED
}
